---
- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

# - name: Read join command from local file
#   slurp:
#     src: "./k8s-join-command"
#   register: k8s_join_command_content
#   when: not kubelet_conf.stat.exists
#   delegate_to: localhost
#   become: no

- name: Get join command from master
  shell: kubeadm token create --print-join-command
  register: k8s_join_command_from_master
  delegate_to: "{{ groups['masters'][0] }}"
  become: yes
  when: not kubelet_conf.stat.exists

- name: Join Kubernetes cluster
  shell: "{{ k8s_join_command_from_master.stdout }}"
  when: not kubelet_conf.stat.exists and k8s_join_command_from_master is defined

# - name: Join Kubernetes cluster
#   shell: "{{ k8s_join_command_content.content | b64decode | trim }}"
#   when: not kubelet_conf.stat.exists and k8s_join_command_content is defined

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started